export type dataType = {
  title: string
  artist: string
  text: string
}
export default [
  {
    title: "Position",
    artist: "Ariana Grande",
    text: `Heaven sent you to me I'm just hopin' I don't repeat history Boy, I'm tryna meet your mama on a Sunday Then make a lotta love on a Monday (ah-ah) Never need no (no), no one else, babe 'Cause I'll be Switchin' the positions for you Cookin' in the kitchen and I'm in the bedroom I'm in the Olympics, way I'm jumpin' through hoops Know my love infinite, nothin' I wouldn't do That I won't do, switchin' for you Perfect, perfect You're too good to be true (you're too good to be true) But I get tired of runnin' Fuck it, now I'm runnin' with you (wit' you) Said, boy, I'm tryna meet your mama on a Sunday Then make a lotta love on a Monday (ah-ah) Never need no (no), no one else, babе 'Cause I'll be Switchin' the positions for you (for you, ah) Cookin' in thе kitchen and I'm in the bedroom I'm in the Olympics, way I'm jumpin' through hoops Know my love infinite, nothing I wouldn't do That I won't do, switchin' for you Cookin' in the kitchen and I'm in the bedroom (bedroom) I'm in the Olympics way, I'm jumpin' through hoops Know my love infinite, nothing I wouldn't do That I won't do, switching for you This some shit that I usually don't do (yeah) But for you, I kinda, kinda want to 'Cause you're down for me and I'm down too (and I'm down too) Yeah, I'm down too, switching the positions for you This some shit that I (yeah) usually don't do (don't do) But for you, I kinda, kinda want to 'Cause you're down for me and I'm down too Switchin' the positions for you Cookin' in the kitchen and I'm in the bedroom I'm in the Olympics way, I'm jumpin' through hoops (to you, to you) Know my love infinite, nothing I wouldn't do (do) That I won't do, switchin' for you Cookin' in the kitchen and I'm in the bedroom I'm in the Olympics way, I'm jumpin' through hoops Know my love infinite, nothin' I wouldn't do That I won't do, switchin' for you Yeah Ah, yeah Ah (ah), yeah`,
  },
  {
    title: "Shut Up",
    artist: "Ariana Grande",
    text: `My presence sweet and my aura bright Diamonds good for my appetite Guess it fuckin' just clicked one night All them demons helped me see shit differently So don't be sad for me How you been spending your time ? (How ?) How you be using your tongue ? (How ?) You be so worried 'bout mine (Mine) Can't even get yourself none You know you sound so dumb (So dumb, so dumb) You know you sound so dumb (So dumb) So maybe you should shut up, mmm Yeah, maybe you should shut up Said if only you would shut up (Mmm) Yeah, that's right, you should shut up (Ah) I vibrate high and my circle lit We ain't really with drugs and shit Love the game so I ain't nevеr miss Keep opinions muted for the hell of it 'Causе I like my shit (Mmm, yep) How you been spending your time ? (How ?) How you be using your tongue ? (How ?) You be so worried 'bout mine (Mine) Can't even get yourself none You know you sound so dumb (So dumb, so dumb) You know you sound so dumb (So dumb) So maybe you should shut up, mmm Yeah, maybe you should shut up Said if only you would shut up (Mmm) Yeah, that's right, you should shut up (Ah)`,
  },
  {
    title: "34 + 35",
    artist: "Ariana Grande",
    text: `You might think I'm crazy The way I've been cravin' If I put it quite plainly Just gimme them babies So what you doin' tonight ? Better say, "Doin' you right" (Yeah) Watchin' movies, but we ain't seen a thing tonight (Yeah) I don't wanna keep you up (You up) But show me, can you keep it up ? (It up) 'Cause then I'll have to keep you up Shit, maybe I'ma keep you up, boy I've been drinkin' coffee (I've been drinkin' coffee; coffee) And I've been eatin' healthy (I've been eatin' healthy; healthy) You know I keep it squeaky, yeah (You know I keep it squeaky) Savin' up my energy (Yeah, yeah, savin' up my energy) Can you stay up all night ? Fuck me 'til the daylight Thirty-four, thirty-five (Yeah, yeah, yeah, yeah) Can you stay up all night ? (All night) Fuck mе 'til the daylight Thirty-four, thirty-five (Yeah, yеah, yeah, yeah) You drink it just like water (Water) You say it tastes like candy So what you doin' tonight ? (Tonight) Better say, "Doin' you right" (Alright) Watchin' movies, but we ain't seen a thing tonight (Yeah) I don't wanna keep you up (You up) But show me, can you keep it up ? (It up) 'Cause then I'll have to keep you up Shit, maybe I'ma keep you up, boy I've been drinkin' coffee (Said I've been drinkin' coffee; coffee) And I've been eatin' healthy (And I've been eatin' healthy; healthy) You know I keep it squeaky, yeah (Except this wine, babe) Savin' up my energy (Yeah, yeah, yeah) Can you stay up all night ? (All night) Fuck me 'til the daylight (Daylight) Thirty-four, thirty-five (Thirty-five; yeah, yeah, yeah, yeah) Can you stay up all night ? (Can you stay ?) Fuck me 'til the daylight (Can you stay ?) Thirty-four, thirty-five (Yeah, yeah, yeah, yeah) Oh yeah, yeah Baby, you might need a seatbelt when I ride it I'ma leave it open like a door, come inside it Even though I'm wifey, you can hit it like a side chick Don't need no side dick, no Got the neighbors yellin' "Earthquake!" (Earthquake) 4.5 when I make the bed shake Put it down heavy even though it's lightweight (It's lightweight, yeah, yeah, yeah, babe) Yeah, we started at midnight Go 'til the sunrise (Sunrise) Done at the same time (Yeah) But who's counting the time when we got it for life ? (Got it for life) I know all your favorite spots (Favorite spots) We can take it from the top (From the top) You such a dream come true, true Make a bitch wanna hit snooze, ooh Can you stay up all night ? Fuck me 'til the daylight (Yeah, yeah) Thirty-four, thirty-five (Yeah, yeah, yeah, yeah) (Thirty-four, thirty-five) Can you stay up all night ? (Do you know what that means ?) Fuck me 'til the daylight (Do you know what that means ?) Thirty-four, thirty-five (Yeah, yeah, yeah, yeah) Yeah, yeah, yeah Means I wanna "69" with you No shit Math class Never was good`,
  },
]
